server:
  port: 8081
logging:
  config: classpath:logback.xml
xxl:
  job:
    executor:
      logpath: /data/applogs/xxl-job/jobhandler
      appname: app-pay-job
      port: 9999
      logretentiondays: -1
      ip: 
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken: